In [3]:
import pandas as pd
import numpy as np
import os
import json
import altair as alt
import glob

In [4]:
MEME_RESULT_JSONS = glob.glob(os.path.join("..", "results", "mammalian_REV3L", "*.MEME.json"))

print(MEME_RESULT_JSONS)

['..\\results\\mammalian_REV3L\\mammalian_REV3L.2.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.12.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.4.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.1.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.5.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.13.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.7.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.10.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.14.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.11.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.8.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.6.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.9.codon.fas.MEME.json', '..\\results\\mammalian_REV3L\\mammalian_REV3L.3.codon.fas.MEME.json']

In [5]:
def getMEMEData(json_file):
    # assert that the file exists
    with open(json_file, "r") as in_d:
        json_data = json.load(in_d)
    return json_data["MLE"]["content"]["0"]
#end method

def getMEMEHeaders(json_file):
    # assert that the file exists
    with open(json_file, "r") as in_d:
        json_data = json.load(in_d)
    return json_data["MLE"]["headers"]
#end method

In [6]:
df_holder = []
for i in range(1, len(MEME_RESULT_JSONS) + 1):
    #print(i)
    file = os.path.join("..", "results", "mammalian_REV3L", "mammalian_REV3L." + str(i) + ".codon.fas.MEME.json")
    print("# Opening;", file)
    columns = getMEMEHeaders(file)
    headers = [x[0] for x in columns]
    df = pd.DataFrame(getMEMEData(file), columns=headers, dtype = float)
    df_holder.append(df)

# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.1.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.2.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.3.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.4.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.5.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.6.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.7.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.8.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.9.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.10.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.11.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.12.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.13.codon.fas.MEME.json
# Opening; ..\results\mammalian_REV3L\mammalian_REV3L.14.codon.fas.MEME.json

In [7]:
df_main = pd.concat(df_holder)
df_main = df_main.reset_index(drop=True)
df_main.index += 1
df_main["Site"] = df_main.index
#df_main.to_csv("AOC-REV3L_FELResults_all.csv")
df_main

,&alpha;,&beta;<sup>-</sup>,p<sup>-</sup>,&beta;<sup>+</sup>,p<sup>+</sup>,LRT,p-value,# branches under selection,Total branch length,MEME LogL,FEL LogL,Variation p,Site
1,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.0,0.000000,0.000000,1.000000,1
2,2.258532,0.000000,0.902097,3.862035,0.097903,0.115052,0.566508,2.0,0.0,-34.611972,-33.201309,0.243981,2
3,1.791995,0.322203,1.000000,2.687992,0.000000,0.000000,0.666667,0.0,0.0,-51.215847,-51.215847,1.000000,3
4,0.489847,0.455488,1.000000,0.734770,0.000000,0.000000,0.666667,0.0,0.0,-29.915570,-29.915570,1.000000,4
5,2.862225,0.000000,1.000000,4.293337,0.000000,0.000000,0.666667,0.0,0.0,-42.547689,-42.547689,1.000000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3624,0.457401,0.000000,1.000000,0.686101,0.000000,0.000000,0.666667,0.0,0.0,-24.230463,-24.230463,1.000000,3624
3625,0.372063,0.000000,1.000000,0.558094,0.000000,0.000000,0.666667,0.0,0.0,-27.688075,-27.688075,1.000000,3625
3626,0.350298,0.043488,1.000000,0.525447,0.000000,0.000000,0.666667,0.0,0.0,-21.745064,-21.745064,1.000000,3626
3627,0.384832,0.063486,1.000000,0.577247,0.000000,0.000000,0.666667,0.0,0.0,-24.278930,-24.278930,1.000000,3627
3628,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.0,0.000000,0.000000,1.000000,3628

In [8]:
df_main.to_csv("AOC-REV3L_MEMEResults_all.csv")

In [10]:
df_main = df_main.rename(columns={"p-value": "p_value"})

In [11]:
df_main = df_main.astype(float)
df_main

,&alpha;,&beta;<sup>-</sup>,p<sup>-</sup>,&beta;<sup>+</sup>,p<sup>+</sup>,LRT,p_value,# branches under selection,Total branch length,MEME LogL,FEL LogL,Variation p,Site
1,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.0,0.000000,0.000000,1.000000,1.0
2,2.258532,0.000000,0.902097,3.862035,0.097903,0.115052,0.566508,2.0,0.0,-34.611972,-33.201309,0.243981,2.0
3,1.791995,0.322203,1.000000,2.687992,0.000000,0.000000,0.666667,0.0,0.0,-51.215847,-51.215847,1.000000,3.0
4,0.489847,0.455488,1.000000,0.734770,0.000000,0.000000,0.666667,0.0,0.0,-29.915570,-29.915570,1.000000,4.0
5,2.862225,0.000000,1.000000,4.293337,0.000000,0.000000,0.666667,0.0,0.0,-42.547689,-42.547689,1.000000,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3624,0.457401,0.000000,1.000000,0.686101,0.000000,0.000000,0.666667,0.0,0.0,-24.230463,-24.230463,1.000000,3624.0
3625,0.372063,0.000000,1.000000,0.558094,0.000000,0.000000,0.666667,0.0,0.0,-27.688075,-27.688075,1.000000,3625.0
3626,0.350298,0.043488,1.000000,0.525447,0.000000,0.000000,0.666667,0.0,0.0,-21.745064,-21.745064,1.000000,3626.0
3627,0.384832,0.063486,1.000000,0.577247,0.000000,0.000000,0.666667,0.0,0.0,-24.278930,-24.278930,1.000000,3627.0
3628,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.0,0.000000,0.000000,1.000000,3628.0

In [13]:
source = df_main

line = alt.Chart(source).mark_circle().encode(
    x='Site',
    y = alt.Y('p_value', scale=alt.Scale(domain=[0, 1], clamp=False)),
    #color = alt.Color('p_value', scale=alt.Scale(reverse=True))  
    
    color = alt.condition((alt.datum.p_value <= 0.1), 
                                alt.ColorValue('red'), 
                                alt.ColorValue('lightgray'))
    
    
).properties(
    width=800,
    height=600)


#band = alt.Chart(source).mark_area(opacity=0.5).encode(x='Site',
#                                                       y='dN/dS LB', 
#                                                       y2='dN/dS UB',
#                                                       color = alt.condition((alt.datum.p_value <= 0.1), 
#                                                            alt.ColorValue('red'), 
#                                                            alt.ColorValue('lightgray')))

#save(line+band, "FEL_all.png")
#line+band
#ine+band
line

alt.Chart(...)